# Sample workflow for building and deploying a Jekyll site with PHP and MySQL
name: Deploy Jekyll with PHP and MySQL support

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job with PHP and MySQL setup
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        
      - name: Instalar PHP e extensões
        run: sudo apt-get install -y php php-mysql
        
      - name: Configurar MySQL
        run: |
          sudo systemctl start mysql
          mysql -u root -e "CREATE DATABASE meu_banco;"
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Build com Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
