name: Deploy Jekyll with PHP, MySQL, and SSH

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        
      - name: Instalar PHP e MySQL
        run: sudo apt-get install -y php php-mysql
        
      - name: Configurar MySQL
        run: |
          sudo systemctl start mysql
          mysql -u root -e "CREATE DATABASE meu_banco;"
      
      - name: Instalar e Configurar SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server
          sudo systemctl start ssh
          sudo systemctl enable ssh
          echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
          echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config
          sudo systemctl restart ssh
      
      - name: Criar usuário SSH e senha
        run: |
          sudo useradd -m -s /bin/bash meu_usuario
          echo "meu_usuario:minha_senha_segura" | sudo chpasswd
          
      - name: Obter IP e porta SSH
        run: |
          echo "Endereço IP:"
          hostname -I
          echo "Porta SSH:"
          sudo grep ^Port /etc/ssh/sshd_config || echo "Padrão: 22"
      
      - name: Build com Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy para GitHub Pages
        uses: actions/deploy-pages@v4
